version: "3.1"

services:
  api:
    build: ./api/
    ports:
      - "${PORT}:9001"
    depends_on:
      - db
    external_links:
      - db:docker-mysql
    env_file:
      - ./.env
    environment:
      - DATABASE_HOST=db
      - DB_HOST=docker-mysql
    volumes:
      - ./api:/api
      - /api/node_modules
  db:
    build: ./database
    env_file:
      - ./.env
